name = "alcanciapp-api"
main = "src/index.js"
compatibility_date = "2024-02-20"

[vars]
CORS_ORIGIN = "*"

[[d1_databases]]
binding = "DB"
database_name = "alcanciapp-d1"
database_id = "local-d1-placeholder" # Requerido localmente, se sobreescribe en prod
